---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: nu-was-demo-hitcount-rt
spec:
  to:
    kind: Service
    name: nu-was-demo-hitcount-svc
    weight: 100
  port:
    targetPort: 9080
  wildcardPolicy: None
  path: /hitcount